technical_university/accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^login/$',
        view=views.LoginView.as_view(),
        name='login',
    ),
    url(
        regex=r'^(?P<slug>[\w-]+)/password-change/$',
        view=views.PasswordChangeView.as_view(),
        name='password-change',
    ),
]

technical_university/technical_university/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^hades/', admin.site.urls),

    url(r'^i18n/', include('django.conf.urls.i18n')),

    url('^', include('accounts.urls',
                     namespace='accounts')),

    url('^accounts/', include('django.contrib.auth.urls')),

    url(r'^departament/', include('departments.urls',
                                  namespace='departament')),
    url(r'^profile/', include('profiles.urls',
                              namespace='profile'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

technical_university/templates/__base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}</title>

    <!--     Fonts and icons     -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"/>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css"/>

    <!-- CSS Files -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/material-kit.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

    {% block css %} {% endblock css %}
</head>
<body>

{% include '_navigationbar.html' with object=departament %}


{% block messages %}
{% endblock messages %}

{% block content %}
{% endblock content %}


</body>

<script src="{% static 'js/particles.js' %}"></script>
<!--   Core JS Files   -->
<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/material.min.js' %}"></script>

<script src="{% static 'js/material-kit.js' %} " type="text/javascript"></script>

{% block javascript %}{% endblock javascript %}

<script>
    particlesJS.load('particles-js', '{% static 'js/particlesjs-config.json' %}', function () {
        console.log('callback - particles.js config loaded');
    });</script>
</html>

technical_university/templates/_edit_background.html
{% load static %}
<div class="header header-filter"
     style="background-image: url('{% static 'img/edit-background.jpg' %}');">
    <div class="container">
    </div>
</div>

technical_university/templates/_navigationbar.html
{% load static i18n %}
<nav class="navbar navbar-info navbar-transparent navbar-fixed-top navbar-color-on-scroll">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            {# LOGO #}
            <a class="navbar-brand" href="http://www.tu-sliven.com/">ТУ-София ИПФ-Сливен</a>
        </div>

        <div class="collapse navbar-collapse" id="navigation-example">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{{ object.get_absolute_url }}" target="">
                        {% trans 'Home' %}
                    </a>
                </li>
                <li>
                    <a href="{{ object.get_structure_url }}" target="">
                        {% trans 'Structure' %}
                    </a>
                </li>
                {% if False %}
                    <li>
                        <a href="{{ object.get_laboratories_url }}" target="">
                            {% if object.is_teachers_department %} Лаборатории {% else %} Стая {% endif %}
                        </a>
                    </li>
                    <li>
                        <a href="{{ object.get_history_url }}" target="">
                            {% trans 'News' %}
                        </a>
                    </li>
                    <li>
                        <a href="{{ object.get_history_url }}" target="">
                            {% trans 'History' %}
                        </a>
                    </li>
                {% endif %}

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="material-icons">account_circle</i>

                        {% trans 'Profile' %}
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        {% if user.is_authenticated and user.userprofile.profile %}
                            <li><a href="{{ user.userprofile.get_absolute_url }}">Към профила</a></li>
                            <li><a href="{{ user.userprofile.profile.get_edit_url }}">Редактиране на профила</a></li>
                            {% if user %}
                                {% if user.userprofile.profile.is_teacher %}
                                    <li>
                                        <a href="{{ user.userprofile.profile.get_publication_edit_url }}">{% trans 'Edit publications' %}</a>
                                    </li>
                                {% endif %}
                                <li>
                                    <a href="{{ user.userprofile.profile.get_password_change_url }}">{% trans 'Change password' %}</a>
                                </li>
                                <li class="divider"></li>
                                {% if user.is_staff %}
                                    <li>
                                        <a href="{{ user.userprofile.get_departament.get_edit_url }}">{% trans 'Edit departament' %}</a>
                                    </li>
                                    {% if user.userprofile.profile.is_teacher %}
                                        <li><a href="{{ user.userprofile.profile.get_school_subject_edit_url }}">{% trans 'Edit Subjects' %}</a>
                                        </li>
                                    {% endif %}
                                    <li><a href="{{ user.userprofile.get_absolute_url }}">Редактиране на зали</a></li>
                                    <li class="divider"></li>
                                {% endif %}
                            {% endif %}
                            <li><a href="{% url 'logout' %}">{% trans 'Logout profile' %}</a></li>
                        {% else %}
                            <li><a href="{% url 'accounts:login' %}">{% trans 'Login profile' %}</a></li>
                        {% endif %}

                    </ul>

                </li>
            </ul>
        </div>
    </div>
</nav>