technical_university/accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^login/$',
        view=views.LoginView.as_view(),
        name='login',
    ),
    url(
        regex=r'^(?P<slug>[\w-]+)/password-change/$',
        view=views.PasswordChangeView.as_view(),
        name='password-change',
    ),
]

technical_university/departments/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^(?P<slug>[\w-]+)/$',
        view=views.HomeView.as_view(),
        name='home',
    ),
    url(
        regex=r'^(?P<slug>[\w-]+)/edit/$',
        view=views.HomeEditView.as_view(),
        name='home_edit',
    ),
    url(
        regex=r'^(?P<slug>[\w-]+)/structure/$',
        view=views.StructureView.as_view(),
        name='structure'
    ),
    url(
        regex=r'(?P<slug>[\w-]+)/history/$',
        view=views.HistoryView.as_view(),
        name='history'
    ),
    url(
        regex=r'(?P<slug>[\w-]+)/laboratories/$',
        view=views.LaboratoriesView.as_view(),
        name='laboratories'
    ),
    url(
        regex=r'(?P<slug>[\w-]+)/school-subjects/list/$',
        view=views.SchoolSubjectListEditView.as_view(),
        name='school_subjects_list'
    ),
    url(
        regex=r'(?P<slug>[\w-]+)/school-subject/create/$',
        view=views.SchoolSubjectCreateView.as_view(),
        name='school_subjects_create'
    ),

    url(
        regex=r'(?P<slug>[\w-]+)/school-subject/(?P<pk>\d+)/edit/$',
        view=views.SchoolSubjectUpdateView.as_view(),
        name='school_subjects_edit'
    ),
    url(
        regex=r'(?P<slug>[\w-]+)/news/$',
        view=views.NewsListView.as_view(),
        name='news_list'
    )
]

technical_university/technical_university/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^hades/', admin.site.urls),

    url(r'^i18n/', include('django.conf.urls.i18n')),

    url('^', include('accounts.urls',
                     namespace='accounts')),

    url('^accounts/', include('django.contrib.auth.urls')),

    url(r'^departament/', include('departments.urls',
                                  namespace='departament')),
    url(r'^profile/', include('profiles.urls',
                              namespace='profile'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

technical_university/departments/models.py
import os
from transliterate import translit

from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.utils.translation import ugettext_lazy as _
from django.urls.base import reverse
from django.utils.text import slugify

from news.models import News
from profiles.models import Profile, TeacherProfile


def cover_image_upload_location(instance, filename):
    save_url = os.path.join(instance.slug, filename)
    return save_url


class Departament(models.Model):
    class Meta:
        verbose_name = _('departament')
        verbose_name_plural = _('departaments')

    slug = models.SlugField(unique=True, null=False, blank=True, verbose_name=_('slug'))
    title = models.CharField(max_length=150, verbose_name=_('title'))
    content = models.TextField(verbose_name=_('content'))
    struct_info = models.TextField(blank=True, default='', verbose_name=_('structure info'))
    cover_image = models.ImageField(upload_to=cover_image_upload_location, verbose_name=_('cover image'))

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('departament:home', kwargs={'slug': self.slug})

    def get_structure_url(self):
        return reverse('departament:structure', kwargs={'slug': self.slug})

    def get_laboratories_url(self):
        return reverse('departament:laboratories', kwargs={'slug': self.slug})

    def get_history_url(self):
        return reverse('departament:history', kwargs={'slug': self.slug})

    def get_edit_url(self):
        return reverse('departament:home_edit', kwargs={'slug': self.slug})

    @property
    def is_teachers_department(self):
        try:
            return self.departamentleader.leader.is_teacher
        except models.FieldDoesNotExist:
            return False


# TODO: Make sure that the slug is unique
@receiver(signal=pre_save, sender=Departament)
def department_slug_receiver(sender, instance, *args, **kwargs):
    title_split = instance.title.split()
    initials = [word[0] for word in title_split if len(word) > 1]
    initials = "".join(initials)
    slug = slugify(translit(initials, reversed=True))
    instance.slug = slug


class DepartamentLeader(models.Model):
    class Meta:
        verbose_name = _('departament leader')
        verbose_name_plural = _('departament leaders')

    departament = models.OneToOneField(Departament, verbose_name=_('departament'))
    leader = models.OneToOneField(Profile, verbose_name=_('leader'))

    def __str__(self):
        return "{}: {}".format(self.departament.title, self.leader.get_full_name)


class DepartamentProfile(models.Model):
    class Meta:
        verbose_name = _('departament profile')
        verbose_name_plural = _('departament profiles')

    departament = models.ForeignKey(Departament, verbose_name=_('departament'))
    profile = models.OneToOneField(Profile, verbose_name=_('profile'))

    def __str__(self):
        return self.profile.get_full_name


class SchoolSubject(models.Model):
    class Meta:
        verbose_name = _('school subject')
        verbose_name_plural = _('school subjects')

    departament = models.ForeignKey(Departament, verbose_name=_('departament'))
    teachers = models.ManyToManyField(TeacherProfile, verbose_name=_('teachers'))
    title = models.CharField(max_length=225, verbose_name=_('title'))
    description = models.TextField(verbose_name=_('description'))


class Laboratory(models.Model):
    class Meta:
        verbose_name = _('Laboratory')
        verbose_name_plural = _('Laboratories')

    department = models.ForeignKey(Departament, verbose_name=_('departament'))
    room_number = models.CharField(max_length=4, verbose_name=_('room number'))
    subject_name = models.CharField(max_length=225, verbose_name=_('subject name'))


class LaboratoryImage(models.Model):
    class Meta:
        verbose_name = _('laboratory image')
        verbose_name_plural = _('laboratory images')

    laboratory = models.ForeignKey(Laboratory, verbose_name=_('laboratory'))
    image = models.ImageField(verbose_name=_('image'))


class DepartamentNews(models.Model):
    departament = models.OneToOneField(Departament)
    news = models.OneToOneField(News)

    def __str__(self):
        return '{}: {}'.format(self.department.title, self.news.title)

technical_university/departments/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from departments.models import Departament, SchoolSubject


class DepartamentModelForm(forms.ModelForm):
    class Meta:
        model = Departament
        fields = ('content', 'struct_info', 'cover_image')
        labels = {
            'content': 'Departament info',
            'struct_info': _('Departament structure info'),
        }


class SchoolSubjectModelForm(forms.ModelForm):
    class Meta:
        model = SchoolSubject
        fields = ('title', 'description', 'teachers',)
        labels = {
            'title': _('School subject name'),
            'description': _('Description'),
            'teachers': _('Teachers'),
        }


class SchoolSubjectListForm(forms.Form):
    school_subject = forms.ModelChoiceField(queryset=SchoolSubject.objects.none())

    def __init__(self, school_subject_qs, **kwargs):
        super(SchoolSubjectListForm, self).__init__(**kwargs)
        self.fields['school_subject'].queryset = school_subject_qs

technical_university/departments/views.py
from django.contrib.auth.mixins import AccessMixin
from django.http import Http404
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.views.generic import DetailView, UpdateView
from django.views.generic import FormView
from django.views.generic import ListView

from departments.forms import DepartamentModelForm, SchoolSubjectListForm, SchoolSubjectModelForm
from news.models import News
from profiles.models import Profile
from technical_university.mixins import StaffCurrentDepartamentUserLoginRequiredMixin
from .models import Departament, SchoolSubject


class HomeView(DetailView):
    model = Departament
    template_name = 'departments/home.html'


class HomeEditView(AccessMixin, UpdateView):
    model = Departament
    form_class = DepartamentModelForm
    template_name = 'departments/edits/home_edit.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return self.handle_no_permission()
        if not request.user.is_staff:
            raise Http404
        if request.user.userprofile.profile.departamentprofile.departament.slug != self.kwargs.get('slug'):
            raise Http404
        return super(HomeEditView, self).dispatch(request, *args, **kwargs)


class HistoryView(DetailView):
    model = Departament
    template_name = 'departments/history.html'
    title_name = 'History'


class LaboratoriesView(DetailView):
    model = Departament
    template_name = 'departments/laboratory.html'


class StructureView(DetailView):
    model = Departament
    models = Profile
    template_name = 'departments/structure/_section_structure.html'
    object = None

    def get_context_data(self, **kwargs):
        context = super(StructureView, self).get_context_data(**kwargs)

        context['non_existing_message'] = 'Не същестуват участници от дадената графа'

        departament = self.get_object()
        context['departament'] = departament

        leader = departament.departamentleader.leader
        context['leader'] = leader

        profiles_ids = departament.departamentprofile_set.all().exclude(profile=leader).values_list('pk', flat=True)
        profile_qs = Profile.objects.filter(id__in=profiles_ids)
        if leader.is_teacher:
            self._get_teachers_profiles(context, profile_qs)

        elif leader.is_student_council:
            self._get_student_council_profiles(context, profile_qs)
        else:
            context['profiles'] = profile_qs

        return context

    @staticmethod
    def _get_teachers_profiles(context, profile_qs=None):
        context['is_teacher_department'] = True

        context['left_group'] = 'Нехабилитирани'
        context['right_group'] = 'Хабилитирани'
        if profile_qs:
            context['left_group_participants'] = profile_qs.filter(teacher_profile__habilitated=True)
            context['right_group_participants'] = profile_qs.filter(teacher_profile__habilitated=False)

    @staticmethod
    def _get_student_council_profiles(context, profile_qs=None):
        context['is_student_council_department'] = True

        context['left_group'] = 'Факултет'
        context['right_group'] = 'Колеж'

        if profile_qs:
            context['left_group_participants'] = profile_qs(student_council_profile__from_faculty=True)
            context['right_group_participants'] = profile_qs(student_council_profile__from_faculty=False)


class SchoolSubjectListEditView(StaffCurrentDepartamentUserLoginRequiredMixin,
                                ListView):
    ACTION_DELETE = 'delete'

    template_name = 'departments/edits/school_subjects_edit_list.html'
    model = SchoolSubject
    paginate_by = 10
    form_class = SchoolSubjectListForm

    def post(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()
        form = self.form_class(self.get_queryset(), data=request.POST)
        if form.is_valid():
            return self.form_valid(form)
        return self.form_invalid(form)

    def form_valid(self, form):
        form.cleaned_data['school_subject'].delete()
        return redirect(reverse_lazy('departament:school_subjects_list', kwargs={'slug': self.kwargs['slug']}))

    def form_invalid(self, form):
        context = self.get_context_data()
        context['form'] = form
        return self.render_to_response(context)

    def get_queryset(self):
        queryset = super(SchoolSubjectListEditView, self).get_queryset()
        return queryset.filter(departament__slug=self.kwargs.get('slug'))

    def get_context_data(self, **kwargs):
        context = super(SchoolSubjectListEditView, self).get_context_data(**kwargs)
        context['departament'] = get_object_or_404(Departament, slug=self.kwargs.get('slug'))

        return context


class SchoolSubjectCreateView(StaffCurrentDepartamentUserLoginRequiredMixin,
                              FormView):
    template_name = 'departments/edits/school_subject.html'
    form_class = SchoolSubjectModelForm

    def get_context_data(self, **kwargs):
        context = super(SchoolSubjectCreateView, self).get_context_data(**kwargs)
        context['departament'] = get_object_or_404(Departament, slug=self.kwargs.get('slug'))
        return context

    def form_valid(self, form):
        form.save()
        return redirect(
            reverse_lazy(
                'departament:school_subjects_list', kwargs={'slug': self.kwargs.get('dep_slug')})
        )


class SchoolSubjectUpdateView(StaffCurrentDepartamentUserLoginRequiredMixin,
                              UpdateView):
    template_name = 'departments/edits/school_subject.html'
    model = SchoolSubject
    form_class = SchoolSubjectModelForm

    def get_success_url(self):
        return reverse_lazy(
            'departament:school_subjects_list',
            kwargs={'slug': self.kwargs.get('slug')}
        )


class NewsListView(ListView):
    model = News
    template_name = 'departments/news/news_list.html'
    slug_field = 'slug'

    def get_queryset(self):
        qs = super(NewsListView, self).get_queryset()
        return qs.filter(departamentnews__departament__slug=self.get_slug_field())

    def get_context_data(self, **kwargs):
        context = super(NewsListView, self).get_context_data(**kwargs)
        context['departament'] = get_object_or_404(Departament, slug=self.get_slug_field())
        return context

    def get_slug_field(self):
        return self.kwargs.get(self.slug_field)


class NewsListEditView(object):
    pass


class NewsDetailView(DetailView):
    pass


class NewsCreateView(CreateView):
    pass


class NewsUpdateView(UpdateView):
    pass

technical_university/templates/departments/edits/_school_subjects_edit.html
{% extends '__base.html' %}
{% load i18n widget_tweaks %}
{% block content %}

    <div class="wrapper">
        {% include '_edit_background.html' %}
        <div class="main main-raised">
            <div class="container">
                <div class="section section-landing">
                    <div class="col-xs-offset-1 col-xs-10 col-md-8 col-md-offset-2">
                        <h2 class="text-center title">{% trans 'Edit school subjects' %}</h2>
                        {% block data %}
                        {% endblock data %}
                    </div>

                </div>
            </div>
        </div>

        <footer class="footer">
        </footer>

    </div>

{% endblock content %}

technical_university/templates/departments/edits/home_edit.html
{% extends '__base.html' %}
{% load widget_tweaks %}
{% block content %}

    <div class="wrapper">
        {% include '_edit_background.html' %}

        <div class="main main-raised">
            <div class="container">
                <div class="section section-landing">
                    <div class="col-xs-offset-1 col-xs-10 col-md-8 col-md-offset-2">
                        <h2 class="text-center title">Редактиране на катедрата</h2>
                        <form class="contact-form" method="POST" action=".">{% csrf_token %}

                            <div class="form-group label-floating">
                                <label class="control-label">{{ form.content.label }}</label>
                                {{ form.content|attr:'class:form-control'|attr:'rows:10' }}
                            </div>

                            <div class="form-group label-floating">
                                <label class="control-label">{{ form.struct_info.label }}</label>
                                {{ form.struct_info|attr:'class:form-control'|attr:'rows:10' }}
                            </div>

                            <div class="row">
                                <div class="col-sm-4 col-sm-offset-4 text-center">
                                    <input type="submit" class="btn btn-primary btn-raised btn-info" value="Запиши">
                                </div>
                            </div>
                        </form>
                    </div>

                </div>
            </div>
        </div>

        <footer class="footer">
        </footer>

    </div>
{% endblock content %}

technical_university/templates/departments/edits/school_subject.html
{% extends 'departments/edits/_school_subjects_edit.html' %}
{% load widget_tweaks i18n %}

{% block data %}
    <div class="row">
        <form action="." method="POST">{% csrf_token %}
            <input type="hidden" name="departament" value="{{ departament.pk }}">
            <div class="col-xs-12">
                <div class="form-group label-floating">
                    <label class="control-label">{{ form.title.label }}</label>
                    {{ form.title|attr:'class:form-control' }}
                </div>
            </div>
            <div class="col-xs-12">
                <div class="form-group label-floating">
                    <label class="control-label">{{ form.description.label }}</label>
                    {{ form.description|attr:'class:form-control' }}
                </div>
            </div>

            {{ form.teachers }}
            {{ form.teachers.help_text }}
            <button class="btn btn-info">{% trans Save %}</button>
        </form>
    </div>

{% endblock data %}

technical_university/templates/departments/edits/school_subjects_edit_list.html
{% extends 'departments/edits/_school_subjects_edit.html' %}

{% load static i18n pagin_row_calc %}
{% block data %}

    <table class="table">
        <thead>
        <tr>
            <th class="text-center">#</th>
            <th>{% trans 'Subject name' %}</th>
            <th class="text-right">{% trans 'Actions' %}</th>
        </tr>
        </thead>
        <tbody>
        <form action="" method="POST">

            {% for school_subject in page_obj.object_list %}{% csrf_token %}
                <tr>
                    <td class="text-center">{% pagin_row_calc page_obj.number paginator.per_page forloop.counter %}</td>
                    <td>{{ school_subject.title }}</td>
                    <td class="td-actions text-right">
                        <a href="{% url 'departament:school_subjects_edit' user.userprofile.get_departament.slug school_subject.pk %}"
                           rel="tooltip"
                           title="{% trans 'Change' %}" class="btn btn-success btn-simple btn-xs">
                            <i class="fa fa-edit"></i>
                        </a>

                        <button name='school_subject' value="{{ school_subject.pk }}" type="submit" rel="tooltip"
                                title="{% trans 'Remove' %}" class="btn btn-danger btn-simple btn-xs">
                            <i class="fa fa-times"></i>
                        </button>
                    </td>
                </tr>
            {% endfor %}
        </form>
        </tbody>
    </table>


    {% if page_obj.count > 1 %}
        <ul class="pagination pagination-info">
            {% if page_obj.has_previous %}
                <li><a href="?page={{ page_obj.previous_page_number }}"><</a></li>
            {% endif %}

            {% for page_num in page_obj.paginator.page_range %}
                <li {% if page_num|stringformat:'d' == request.GET.page|default:'1' %}class="active" {% endif %}><a
                        href="?page={{ page_num }}">{{ page_num }}</a></li>
            {% endfor %}
            {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number }}">></a></li>
            {% endif %}
        </ul>
    {% endif %}


    <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="current">
                    Page {{ page_obj.number }} {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
    </div>

{% endblock data %}